### ISSUE TITLE
Kill line (C-k) has lag only on locked down corporate PC

### ISSUE THREAD

**Issue by falcomomo** [tuttieee/vscode-emacs-mcx#112] opened 2019-05-12 14:06 UTC
I have been using this extension on my personal PC and also on my work PC.
On my personal PC everything is flawless - I simply could not use VS Code without this extension, and I think it should be integrated (in large part) into the core build.

However, on my work computer there is a serious and noticable lag when performing certain operations (I think) involving the kill ring, but particularly when using kill-line C-k.
After pressing C-k there is maybe a 0.5 second lag before the line is killed, this makes it not possible to perform the standard operation of C-k C-y to copy a line into the kill ring ready to be yanked elsewhere.
If you try to do this, you will just paste the last yank onto the end of the current line, and the kill won't be registered.

I noticed in the source code, and through discussion on github elsewhere a month ago or so, that this extension occassionally calls some windows built-in executable which handles copying and pasting into the system clipboard (I think?).
My idea so far is that when I am using the extension on a (heavily) locked down corporate pc, any time a program calls another executable the signature is scanned by some other program - I believe that every program I run on my pc is logged & monitored in some way.

I am uncertain of how I could test this idea, I did have a go at running the built-in profiler to see which commands were taking up time in VS Code, but I was slightly unsuccessful.
Do you have any idea of how I could test what is going on, or if you're aware of any others having a related issue?

Many thanks,

**Comment by falcomomo** [comment] 2019-05-19 11:30
I ran the profiler and couldn't find anything helpful, but when I ran the Process Explorer, I noticed that pressing C-k multiple times would often start the application clipboard_x86_64 within: tuttieee.emacs-mcx-0.11.3\node_modules\clipboardy\fallbacks\windows
I suppose this is related to the slowdown.
Hope you might be able to help investigate.

**Comment by tuttieee** [comment] 2019-05-20 16:50
Sorry for my late response and thank you for the investigation.

> that this extension occassionally calls some windows built-in executable which handles copying and pasting into the system clipboard (I think?).

> I noticed that pressing C-k multiple times would often start the application clipboard_x86_64 within: tuttieee.emacs-mcx-0.11.3\node_modules\clipboardy\fallbacks\windows

Yes, this extension uses [clipboardy](https://www.npmjs.com/package/clipboardy) library internally and it seems your inspection shows this library makes some troubles.
I found `clipboard_x86_64.exe` in the library (yes, this seems just what you found!) and it is executed every time you type `C-k`.
However, I don't know what this .exe does and exactly why it makes your PC slow...

One more potential problem is that the extension calls clipboardy's API in "sync" way, not "async" ( https://github.com/tuttieee/vscode-emacs-mcx/blob/eb80ff039c5e664cbd9d0f6fc3d8bdb274623e90/src/kill-yank/index.ts#L85-L91 )

I will try to reproduce and fix the problem when I can prepare a windows environment.
However, if you can edit code and contribute to development, it will be very welcome :D

**Comment by debug-ito** [comment] 2020-02-05 01:21
Hi. I think I'm affected by this issue on one of my PCs. I'm not sure it's related to "locked down" thing, though. I use the affected PC at work, but I'm not sure how much monitoring/logging is performed in it. Maybe the affected PC is just too slow to handle clipboardy.

Maybe it's a good idea to inspect clipboardy instead of this extension, to isolate the root cause.

**Comment by debug-ito** [comment] 2020-02-05 01:26
Maybe it's a good idea to use the latest version of clipboardy??

**Comment by kzys** [comment] 2020-02-05 14:14
FYI, #151 will update clipboardy.

**Comment by tuttieee** [comment] 2020-02-19 15:07
I updated clipboardy and released a new version of this extension, 0.14.0.
Please check if this problem still occurs.

**Comment by debug-ito** [comment] 2020-02-20 01:04
Thanks for update!

Unfortunately, the problem still exists in my computer.

- Windows 10 Pro 1809 (x64)
- VSCode 1.42.1
- Awesome Emacs Keymap 0.14.0

**Comment by tuttieee** [comment] 2020-05-04 12:18
Hi, I changed the way to use the clipboard library that is internally used in this extension.
Though I'm not sure it's related to this problem, please try the latest version and check if the problem occurs.

**Comment by debug-ito** [comment] 2020-05-08 01:42
Thanks for your work on this issue!

Unfortunately, I cannot test the update for now because I have to work from home now (due to COVID-19 pandemic, you know). Strangely, the problem does not exist when I use the PC at home, even before version 0.19.5. I use VPN to enter the internal network of our company, so maybe it makes some difference...

**Comment by falcomomo** [comment] 2020-05-08 07:50
This makes an enormous difference to the performance! Thank you for your
work on this, I would not use VS Code without it.

**Comment by tuttieee** [comment] 2020-05-09 12:54
@falcomomo Thank you for reporting! I assume this problem has been resolved and close this issue.
@debug-ito Though I close this issue now, please let me know to reopen it if you find this problem still exists when you test it after the situation become better.

**Closed by tuttieee** 2020-05-09 12:54 UTC

**Comment by debug-ito** [comment] 2020-09-18 08:04
I finally tested my machine and VSCode in our office, and there was no problem. Thanks for great work!
