### ISSUE TITLE
C-k and C-y no longer work on Linux (Fedora) 

### ISSUE THREAD

**Issue by onedigit** [tuttieee/vscode-emacs-mcx#268] opened 2020-04-26 09:26 UTC
https://github.com/tuttieee/vscode-emacs-mcx/issues/260

Thanks for quickly looking into this. Got 0.19.3, but the issue persists.

OS: Fedora Linux 31
Kernel: 5.6.6-200.fc31.x86_64
KDE Plasma version: 5.68.0-1.fc31

**Comment by tuttieee** [comment] 2020-04-26 10:10
@onedigit 
Thank you for reporting again.

However I cannot reproduce the bug with 0.19.3 in my Linux environment (Linux Mint 18.3 Cinnamon)...

Can you share the error log shown in the developer console of VSCode when you hit C-k and C-y?
You can open the developer tools from "Help" -> "Toggle Developer Tools"

**Comment by tuttieee** [comment] 2020-04-26 10:11
@onedigit Thank you for reporting again.
I could reproduce it on my Linux environment and will investigate it.

**Comment by tuttieee** [comment] 2020-04-26 10:23
Ahh, it is because a sufficient permission is not provided to clipboardy's binary.

**Comment by tuttieee** [comment] 2020-04-26 11:41
@onedigit It may have been fixed in 0.19.4 Please check it.

**Comment by onedigit** [comment] 2020-04-26 16:21
@tuttieee, thank you very much for the quick fix. Confirm that it's working now in 0.19.4.  Awesome.

**Closed** 2020-04-26 16:21 UTC
